-- Extended items (ids 14-50) generated from data/fabulus-extended.json
INSERT INTO rpg_items
    (id, name, description, item_type, main_stat, model_path, icon_path, rarity_id, required_level,
     damage_min, damage_max, attack_speed, armor, anim_attack_override,
     sell_value, restore_health, restore_mana, use_cooldown_ms, max_stack)
VALUES
    (14, 'Bronze Dagger', 'A short curved blade favored by rogues and scouts.', 1, 2, NULL, 'models/rpg/icons/items/bronze-dagger.png', 1, 1, 3, 5, 1.2, NULL, NULL, 6, NULL, NULL, NULL, NULL),
    (15, 'Iron Mace', 'A heavy flanged mace that crushes bone and shield alike.', 1, 1, NULL, 'models/rpg/icons/items/iron-mace.png', 1, 2, 5, 9, 0.9, NULL, NULL, 10, NULL, NULL, NULL, NULL),
    (16, 'Steel Longsword', 'A well-balanced blade of polished steel.', 1, 1, NULL, 'models/rpg/icons/items/steel-longsword.png', 2, 3, 8, 13, 1, NULL, NULL, 18, NULL, NULL, NULL, NULL),
    (17, 'Oak Battle Staff', 'A gnarled staff topped with a faintly glowing crystal.', 1, 3, NULL, 'models/rpg/icons/items/oak-battle-staff.png', 2, 4, 6, 10, 1.1, NULL, NULL, 22, NULL, NULL, NULL, NULL),
    (18, 'Serpent Fang Blade', 'A curved sword with a venom-green edge and serpent pommel.', 1, 2, NULL, 'models/rpg/icons/items/serpent-fang-blade.png', 3, 6, 12, 18, 1.1, NULL, NULL, 45, NULL, NULL, NULL, NULL),
    (19, 'Warlord''s Greataxe', 'A massive double-bladed axe forged for champions.', 1, 1, NULL, 'models/rpg/icons/items/warlords-greataxe.png', 4, 8, 18, 26, 0.8, NULL, NULL, 75, NULL, NULL, NULL, NULL),
    (20, 'Dawnbreaker', 'A radiant holy blade said to banish the darkest foes.', 1, 1, NULL, 'models/rpg/icons/items/dawnbreaker.png', 5, 10, 22, 32, 1, NULL, NULL, 120, NULL, NULL, NULL, NULL),
    (21, 'Leather Cap', 'A simple leather cap offering minimal protection.', 2, NULL, NULL, 'models/rpg/icons/items/leather-cap.png', 1, 1, NULL, NULL, NULL, 2, NULL, 5, NULL, NULL, NULL, NULL),
    (22, 'Bronze Helm', 'An open-faced bronze helm with a sturdy nose guard.', 2, NULL, NULL, 'models/rpg/icons/items/bronze-helm.png', 1, 2, NULL, NULL, NULL, 4, NULL, 10, NULL, NULL, NULL, NULL),
    (23, 'Mage Hood', 'A deep blue hood woven with silver arcane thread.', 2, 3, NULL, 'models/rpg/icons/items/mage-hood.png', 2, 3, NULL, NULL, NULL, 1, NULL, 16, NULL, NULL, NULL, NULL),
    (24, 'Steel Greathelm', 'A fully enclosed steel helm with a narrow visor.', 2, 1, NULL, 'models/rpg/icons/items/steel-greathelm.png', 3, 6, NULL, NULL, NULL, 7, NULL, 38, NULL, NULL, NULL, NULL),
    (25, 'Crown of Kings', 'An ornate golden crown set with crimson gemstones.', 2, 4, NULL, 'models/rpg/icons/items/crown-of-kings.png', 4, 9, NULL, NULL, NULL, 5, NULL, 85, NULL, NULL, NULL, NULL),
    (26, 'Traveler''s Vest', 'A worn leather vest suited for long journeys.', 3, NULL, NULL, 'models/rpg/icons/items/travelers-vest.png', 1, 1, NULL, NULL, NULL, 3, NULL, 7, NULL, NULL, NULL, NULL),
    (27, 'Chainmail Hauberk', 'Interlinked steel rings offering reliable protection.', 3, NULL, NULL, 'models/rpg/icons/items/chainmail-hauberk.png', 2, 3, NULL, NULL, NULL, 6, NULL, 20, NULL, NULL, NULL, NULL),
    (28, 'Scholar''s Robe', 'Flowing blue robes embroidered with arcane sigils.', 3, 3, NULL, 'models/rpg/icons/items/scholars-robe.png', 2, 4, NULL, NULL, NULL, 2, NULL, 24, NULL, NULL, NULL, NULL),
    (29, 'Plate Armor', 'Heavy steel plate forged for front-line warriors.', 3, 1, NULL, 'models/rpg/icons/items/plate-armor.png', 3, 7, NULL, NULL, NULL, 10, NULL, 55, NULL, NULL, NULL, NULL),
    (30, 'Aegis of the Ancients', 'A legendary breastplate engraved with glowing runes.', 3, 4, NULL, 'models/rpg/icons/items/aegis-of-the-ancients.png', 5, 10, NULL, NULL, NULL, 14, NULL, 130, NULL, NULL, NULL, NULL),
    (31, 'Worn Sandals', 'Simple leather sandals, light on the feet.', 4, 2, NULL, 'models/rpg/icons/items/worn-sandals.png', 1, 1, NULL, NULL, NULL, 1, NULL, 4, NULL, NULL, NULL, NULL),
    (32, 'Hide Boots', 'Sturdy hide boots with fur trim for cold trails.', 4, NULL, NULL, 'models/rpg/icons/items/hide-boots.png', 1, 2, NULL, NULL, NULL, 3, NULL, 9, NULL, NULL, NULL, NULL),
    (33, 'Swiftstride Boots', 'Sleek green boots that quicken every step.', 4, 2, NULL, 'models/rpg/icons/items/swiftstride-boots.png', 2, 4, NULL, NULL, NULL, 3, NULL, 20, NULL, NULL, NULL, NULL),
    (34, 'Greaves of Valor', 'Steel greaves worn by knights of the royal guard.', 4, 1, NULL, 'models/rpg/icons/items/greaves-of-valor.png', 3, 6, NULL, NULL, NULL, 5, NULL, 35, NULL, NULL, NULL, NULL),
    (35, 'Boots of the Tempest', 'Light boots crackling with storm energy.', 4, 2, NULL, 'models/rpg/icons/items/boots-of-the-tempest.png', 4, 9, NULL, NULL, NULL, 4, NULL, 70, NULL, NULL, NULL, NULL),
    (36, 'Copper Band', 'A simple polished copper ring.', 5, 1, NULL, 'models/rpg/icons/items/copper-band.png', 1, 1, NULL, NULL, NULL, NULL, NULL, 6, NULL, NULL, NULL, NULL),
    (37, 'Ring of Focus', 'A silver ring set with a glowing blue sapphire.', 5, 3, NULL, 'models/rpg/icons/items/ring-of-focus.png', 2, 3, NULL, NULL, NULL, NULL, NULL, 18, NULL, NULL, NULL, NULL),
    (38, 'Band of Vitality', 'A golden ring set with a deep green emerald.', 5, 4, NULL, 'models/rpg/icons/items/band-of-vitality.png', 2, 5, NULL, NULL, NULL, NULL, NULL, 25, NULL, NULL, NULL, NULL),
    (39, 'Signet of Fury', 'A dark iron signet ring set with a glowing ruby.', 5, 1, NULL, 'models/rpg/icons/items/signet-of-fury.png', 3, 7, NULL, NULL, NULL, NULL, NULL, 50, NULL, NULL, NULL, NULL),
    (40, 'Ring of the Archmage', 'An elaborate golden ring with a violet arcane gem.', 5, 3, NULL, 'models/rpg/icons/items/ring-of-the-archmage.png', 4, 10, NULL, NULL, NULL, NULL, NULL, 90, NULL, NULL, NULL, NULL),
    (41, 'Wooden Pendant', 'A carved wooden talisman on a leather cord.', 6, NULL, NULL, 'models/rpg/icons/items/wooden-pendant.png', 1, 1, NULL, NULL, NULL, NULL, NULL, 5, NULL, NULL, NULL, NULL),
    (42, 'Amulet of Warding', 'A silver shield-shaped amulet on a heavy chain.', 6, 4, NULL, 'models/rpg/icons/items/amulet-of-warding.png', 2, 3, NULL, NULL, NULL, NULL, NULL, 16, NULL, NULL, NULL, NULL),
    (43, 'Pendant of Power', 'A golden amulet radiating raw strength.', 6, 1, NULL, 'models/rpg/icons/items/pendant-of-power.png', 3, 6, NULL, NULL, NULL, NULL, NULL, 42, NULL, NULL, NULL, NULL),
    (44, 'Heart of the Phoenix', 'A legendary phoenix amulet pulsing with fiery life.', 6, 4, NULL, 'models/rpg/icons/items/heart-of-the-phoenix.png', 5, 10, NULL, NULL, NULL, NULL, NULL, 110, NULL, NULL, NULL, NULL),
    (45, 'Iron Targe', 'A small round iron shield with a central boss.', 7, NULL, NULL, 'models/rpg/icons/items/iron-targe.png', 1, 2, NULL, NULL, NULL, 6, NULL, 10, NULL, NULL, NULL, NULL),
    (46, 'Spellbook of Embers', 'A leather-bound tome leaking fiery embers.', 7, 3, NULL, 'models/rpg/icons/items/spellbook-of-embers.png', 2, 4, NULL, NULL, NULL, NULL, NULL, 22, NULL, NULL, NULL, NULL),
    (47, 'Tower Shield', 'A tall rectangular shield of banded steel.', 7, 4, NULL, 'models/rpg/icons/items/tower-shield.png', 3, 7, NULL, NULL, NULL, 12, NULL, 48, NULL, NULL, NULL, NULL),
    (48, 'Bulwark of the Guardian', 'A legendary golden kite shield engraved with a lion.', 7, 4, NULL, 'models/rpg/icons/items/bulwark-of-the-guardian.png', 5, 10, NULL, NULL, NULL, 16, NULL, 115, NULL, NULL, NULL, NULL),
    (49, 'Greater Mana Potion', 'A large vial of swirling blue essence. Restores mana.', 8, NULL, NULL, 'models/rpg/icons/items/greater-mana-potion.png', 2, 5, NULL, NULL, NULL, NULL, NULL, 8, NULL, 80, 5000, 10),
    (50, 'Elixir of Renewal', 'A golden elixir that mends body and spirit alike.', 8, NULL, NULL, 'models/rpg/icons/items/elixir-of-renewal.png', 3, 8, NULL, NULL, NULL, NULL, NULL, 25, 100, 50, 8000, 5)
ON DUPLICATE KEY UPDATE
    name = VALUES(name), description = VALUES(description), item_type = VALUES(item_type),
    main_stat = VALUES(main_stat), model_path = VALUES(model_path), icon_path = VALUES(icon_path), rarity_id = VALUES(rarity_id),
    required_level = VALUES(required_level), damage_min = VALUES(damage_min), damage_max = VALUES(damage_max),
    attack_speed = VALUES(attack_speed), armor = VALUES(armor), anim_attack_override = VALUES(anim_attack_override),
    sell_value = VALUES(sell_value), restore_health = VALUES(restore_health), restore_mana = VALUES(restore_mana),
    use_cooldown_ms = VALUES(use_cooldown_ms), max_stack = VALUES(max_stack);

INSERT INTO rpg_item_modifiers (item_id, attribute_type, value, value_type) VALUES
    (17, 3, 2, 1),
    (18, 10, 3, 1),
    (19, 1, 4, 1),
    (20, 8, 8, 2),
    (22, 4, 1, 1),
    (23, 3, 2, 1),
    (23, 6, 8, 1),
    (24, 4, 3, 1),
    (25, 1, 3, 1),
    (25, 4, 3, 1),
    (25, 5, 15, 1),
    (27, 4, 2, 1),
    (28, 3, 3, 1),
    (28, 6, 15, 1),
    (29, 1, 4, 1),
    (30, 4, 5, 1),
    (30, 5, 30, 1),
    (31, 9, 4, 1),
    (33, 9, 10, 1),
    (34, 4, 3, 1),
    (35, 9, 12, 1),
    (35, 2, 2, 1),
    (36, 1, 1, 1),
    (37, 3, 4, 1),
    (37, 6, 8, 1),
    (38, 4, 3, 1),
    (38, 5, 15, 1),
    (39, 1, 4, 1),
    (39, 10, 5, 1),
    (40, 3, 5, 1),
    (40, 6, 20, 1),
    (40, 14, 1, 1),
    (41, 5, 5, 1),
    (42, 5, 15, 1),
    (42, 4, 1, 1),
    (43, 1, 2, 1),
    (43, 2, 2, 1),
    (43, 8, 10, 2),
    (44, 5, 40, 1),
    (44, 13, 2, 1),
    (46, 3, 3, 1),
    (46, 6, 12, 1),
    (47, 4, 4, 1),
    (48, 4, 5, 1),
    (48, 5, 25, 1);

INSERT INTO rpg_loot_tables (id, enemy_id, loot_type, drop_chance_pct, gold_min, gold_max, item_id) VALUES
    (24, 1, 2, 4, NULL, NULL, 14),
    (25, 1, 2, 3, NULL, NULL, 21),
    (26, 1, 2, 3, NULL, NULL, 26),
    (27, 1, 2, 2, NULL, NULL, 31),
    (28, 1, 2, 2, NULL, NULL, 36),
    (29, 1, 2, 2, NULL, NULL, 41),
    (30, 2, 2, 4, NULL, NULL, 15),
    (31, 2, 2, 3, NULL, NULL, 22),
    (32, 2, 2, 3, NULL, NULL, 27),
    (33, 2, 2, 2, NULL, NULL, 45),
    (34, 2, 2, 3, NULL, NULL, 16),
    (35, 2, 2, 2, NULL, NULL, 37),
    (36, 3, 2, 4, NULL, NULL, 17),
    (37, 3, 2, 3, NULL, NULL, 23),
    (38, 3, 2, 3, NULL, NULL, 28),
    (39, 3, 2, 2, NULL, NULL, 33),
    (40, 3, 2, 2, NULL, NULL, 42),
    (41, 3, 2, 2, NULL, NULL, 46),
    (42, 4, 2, 4, NULL, NULL, 18),
    (43, 4, 2, 3, NULL, NULL, 24),
    (44, 4, 2, 3, NULL, NULL, 29),
    (45, 4, 2, 2, NULL, NULL, 34),
    (46, 4, 2, 2, NULL, NULL, 38),
    (47, 4, 2, 2, NULL, NULL, 43),
    (48, 4, 2, 2, NULL, NULL, 47),
    (49, 4, 2, 3, NULL, NULL, 49),
    (50, 2, 2, 2, NULL, NULL, 19),
    (51, 4, 2, 1, NULL, NULL, 20),
    (52, 4, 2, 1, NULL, NULL, 25),
    (53, 4, 2, 1, NULL, NULL, 30),
    (54, 4, 2, 1, NULL, NULL, 35),
    (55, 4, 2, 1, NULL, NULL, 40),
    (56, 4, 2, 1, NULL, NULL, 44),
    (57, 4, 2, 1, NULL, NULL, 48),
    (58, 4, 2, 2, NULL, NULL, 50)
ON DUPLICATE KEY UPDATE
    enemy_id = VALUES(enemy_id), loot_type = VALUES(loot_type), drop_chance_pct = VALUES(drop_chance_pct),
    gold_min = VALUES(gold_min), gold_max = VALUES(gold_max), item_id = VALUES(item_id);
