export const VNE_FALLBACK_MULT_OF_STALL = 4.0;
export const OVERSPEED_CLACKER_INTERVAL_MS = 250;
export const AIRCRAFT_CATEGORY_LIGHT = 0;
export const AIRCRAFT_CATEGORY_TURBOPROP = 1;
export const AIRCRAFT_CATEGORY_JET = 2;
export const AIRCRAFT_CATEGORY_HEAVY_JET = 3;
export const AIRCRAFT_CATEGORY_MILITARY = 4;
export const MMO_FALLBACK_BY_CATEGORY: Record<number, number> = {
    [AIRCRAFT_CATEGORY_LIGHT]: 0.32,
    [AIRCRAFT_CATEGORY_TURBOPROP]: 0.55,
    [AIRCRAFT_CATEGORY_JET]: 0.82,
    [AIRCRAFT_CATEGORY_HEAVY_JET]: 0.86,
    [AIRCRAFT_CATEGORY_MILITARY]: 0.92,
};
export const MMO_FALLBACK_DEFAULT = 0.85;

export const GPWS_CALLOUT_FT = [500, 200, 100, 50, 40, 30, 20, 10];
export const GPWS_MIN_VS_FOR_CALLOUT_FPM = -200;
export const GPWS_SINK_RATE_VS_FPM = -1500;
export const GPWS_PULL_UP_VS_FPM = -3000;
export const GPWS_CALLOUT_REPEAT_MS = 2500;
export const GPWS_ALERT_DURATION_MS = 1500;
export const GPWS_ALERT_TYPE_CALLOUT = 1;
export const GPWS_ALERT_TYPE_SINK = 2;
export const GPWS_ALERT_TYPE_PULL_UP = 3;
