export const VNE_FALLBACK_MULT_OF_STALL = 4.0;
export const OVERSPEED_CLACKER_INTERVAL_MS = 250;
export const OVERSPEED_SUPERSONIC_MMO_MIN = 1.0;
export const OVERSPEED_VNE_CROSSOVER_ALT_FT = 25000;
export const OVERSPEED_MACH_IAS_CROSSOVER = 0.85;
export const AIRCRAFT_CATEGORY_LIGHT = 0;
export const AIRCRAFT_CATEGORY_TURBOPROP = 1;
export const AIRCRAFT_CATEGORY_JET = 2;
export const AIRCRAFT_CATEGORY_HEAVY_JET = 3;
export const AIRCRAFT_CATEGORY_MILITARY = 4;
export const MMO_FALLBACK_BY_CATEGORY: Record<number, number> = {
    [AIRCRAFT_CATEGORY_LIGHT]: 0.32,
    [AIRCRAFT_CATEGORY_TURBOPROP]: 0.55,
    [AIRCRAFT_CATEGORY_JET]: 0.82,
    [AIRCRAFT_CATEGORY_HEAVY_JET]: 0.86,
    [AIRCRAFT_CATEGORY_MILITARY]: 0.92,
};
export const MMO_FALLBACK_DEFAULT = 0.85;

export const GPWS_CALLOUT_FT = [500, 200, 100, 50, 40, 30, 20, 10];
export const GPWS_MIN_VS_FOR_CALLOUT_FPM = -200;
export const GPWS_SINK_RATE_VS_FPM = -1500;
export const GPWS_PULL_UP_VS_FPM = -3000;
export const GPWS_CALLOUT_REPEAT_MS = 2500;
export const GPWS_ALERT_DURATION_MS = 1500;
export const GPWS_ALERT_TYPE_CALLOUT = 1;
export const GPWS_ALERT_TYPE_SINK = 2;
export const GPWS_ALERT_TYPE_PULL_UP = 3;
export const GPWS_ALERT_TYPE_TOO_LOW_GEAR = 4;
export const GPWS_ALERT_TYPE_TOO_LOW_FLAPS = 5;
export const GPWS_ALERT_TYPE_TERRAIN_CLOSURE = 6;
export const GPWS_TOO_LOW_GEAR_AGL_FT = 500;
export const GPWS_TOO_LOW_FLAPS_AGL_FT = 245;
export const GPWS_TOO_LOW_MIN_AGL_FT = 30;
export const GPWS_TOO_LOW_MIN_SPEED_KTS = 60;
export const GPWS_TERRAIN_CLOSURE_FPM = -2000;
export const GPWS_TERRAIN_CLOSURE_MAX_AGL_FT = 2200;
export const GPWS_TERRAIN_CLOSURE_REPEAT_MS = 4000;
export const GPWS_TOO_LOW_REPEAT_MS = 5000;
export const GPWS_APPROACH_DESCENT_FPM = -150;
